feat: expose list/get options for full/basic on schema methods
googleapis/nodejs-pubsub pull request #1291
Opened 2021-05-18 20:18 UTC by feywind

This corrects a review issue in the unreleased PR: https://github.com/googleapis/nodejs-pubsub/pull/1289

2021-05-18 20:22 UTC, feywind commented
@pradn @hongalex Can y'all verify that this meets the desired functionality? Hoping to get the API finished nailing down before releasing it.

2021-05-18 21:48 UTC, hongalex approved these changes
Looks good, thanks! I'll wait for Prad to confirm

2021-05-18 23:13 UTC, feywind commented
Fixing that flaky test is a separate task...

2021-05-19 21:07 UTC, pradn requested changes

2021-05-19 21:07 UTC, pradn commented on src/pubsub.ts
> +    view: google.pubsub.v1.SchemaView = SchemaViews.Full,
Let's use BASIC as the default for ListSchemas.

FULL should be the default for GetSchemas, as this code already does.

2021-05-20 17:37 UTC, pradn approved these changes
Perhaps a test for this behavior?

2021-05-21 01:00 UTC, merged