feat: detect subscription properties and warn for exactly-once
googleapis/nodejs-pubsub pull request #1561
Opened 2022-05-12 19:22 UTC by feywind

This catches the subscription properties from the first delivered message, and warns the user if exactly-once is enabled. This is a feature in progress for the Node library, so the exactly-once features will not be available yet, and incorrectly used semantics may cause problems with an exactly-once subscription.

2022-05-12 22:44 UTC, hongalex commented
LGTM, but should get approval from @mmicatka or @pradn too

2022-05-16 19:44 UTC, pradn requested changes

2022-05-16 19:44 UTC, pradn commented on src/subscriber.ts
> +   * Sets our subscription properties from the first incoming message.
`exactlyOnceDeliveryEnabled` can be changed any time, so we should check every message, not just the first one. You'd need some sort of throttle on the error, ofc.

2022-05-30 19:18 UTC, feywind commented
Pushing this through to get past the 16 test catch-22.

2022-05-30 19:19 UTC, merged