chore: add config for releasing from legacy-v2 branch
googleapis/nodejs-pubsub pull request #1580
Opened 2022-06-09 16:34 UTC by feywind

Work in progress for adding release machinery to the legacy-v2 branch.

2022-06-09 17:30 UTC, chingor13 approved these changes

2022-06-09 17:31 UTC, chingor13 requested changes

2022-06-09 17:31 UTC, chingor13 commented on .github/workflows/ci.yaml
> +        node: [10, 12, 14, 16]
This change you probably want in the legacy branch

2022-09-22 21:25 UTC, feywind commented
@chingor13 Do you mind giving this another look? I moved the build change out to legacy-v2.

https://github.com/googleapis/nodejs-pubsub/blob/legacy-v2/.github/workflows/ci.yaml

2022-09-27 20:56 UTC, chingor13 approved these changes

2022-09-27 21:06 UTC, feywind commented
Owlbot changes: do not want, for this. It basically reverts the whole change =_=

I wonder if we need to do something to keep it from doing that on every PR.

2022-09-27 21:56 UTC, merged