samples: add samples for Cloud Storage ingestion, and a few small fixes
googleapis/nodejs-pubsub pull request #1985
Opened 2024-10-10 22:11 UTC by feywind

This adds TS/JS samples for Cloud Storage ingestion, plus two fixes:
- a paste-o for Kinesis ingestion
- a Typeless bot invocation issue

2024-10-11 15:33 UTC, michaelpri10 requested changes

2024-10-11 15:33 UTC, michaelpri10 commented on samples/createTopicWithCloudStorageIngestion.js
> +async function createTopicWithKinesisIngestion(
"CloudStorage" instead of "Kinesis".

2024-10-11 15:33 UTC, michaelpri10 commented on samples/typescript/createTopicWithCloudStorageIngestion.ts
> +async function createTopicWithKinesisIngestion(
"CloudStorage" instead of "Kinesis".

2024-10-15 18:43 UTC, feywind commented on samples/createTopicWithCloudStorageIngestion.js
> +async function createTopicWithKinesisIngestion(
Doh, thank you.

2024-10-15 18:55 UTC, michaelpri10 approved these changes

2024-10-15 18:55 UTC, michaelpri10 commented
LGTM, thank you!

2024-10-15 19:56 UTC, merged